# Generated by Django 3.1.4 on 2021-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userofapp',
            name='loan_limit',
            field=models.IntegerField(default=0),
        ),
    ]
